#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  StrafeEncoder,  sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ThrowerEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  LeftDriver,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  RightDriver,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port4,           strafeDrive,   tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port6,           liftRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightThrow,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftThrow,     tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "ThrowerControl.c" // Controls the thrower
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "BlueDriverJoyStickControls.c" // User Controls For User Controlled Period
//#include "LEDLightTimers.c" // Led Light Timer for User Control Part
#include "Pid.c" // PID controller program its self explanatory idiot
//#include "LCDDisplay2016.c"

//int autoRoutineID = 0;

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
	//autoRoutineID = getAutoOption();

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}
task autonomous()
{
//	if(autoRoutineID == 0){
/*		strafeMode = true;
		startTask(driving);
		rightDriveSpeed = 80;
		leftDriveSpeed = 50;
		delay(10);
		rightDriveSpeed = 0;
		leftDriveSpeed = 0;
		strafeSpeed = 50;
		delay(750);
		strafeSpeed = -50;
		rightDriveSpeed = 0;
		leftDriveSpeed = 0;
		throwerSpeed = 127;
		delay(7000);
		strafeSpeed = 50;
		rightDriveSpeed = 0;
		leftDriveSpeed = 0;
		throwerSpeed = 127;
		delay(7000);
		strafeSpeed = 0;
		throwerSpeed = 0;
		leftDriveSpeed = 0;
		rightDriveSpeed = 0;
//		forkSpeed = 0;
//	}
//	if(autoRoutineID == 1){
		strafeMode = true;
		startTask(driving);
		rightDriveSpeed = 80;
		leftDriveSpeed = 50;
		delay(10);
		rightDriveSpeed = 0;
		leftDriveSpeed = 0;
		strafeSpeed = -50;
		delay(750);
		strafeSpeed = 50;
		rightDriveSpeed = 0;
		leftDriveSpeed = 0;
		throwerSpeed = 127;
		// delay(7000);
		// strafeSpeed = -50;
		// rightDriveSpeed = 0;
		// leftDriveSpeed = 0;
		// throwerSpeed = 127;
		// delay(7000);
		// strafeSpeed = 0;
		// throwerSpeed = 0;
		// leftDriveSpeed = 0;
		// rightDriveSpeed = 0; */
//	}
}

task usercontrol()
{
		startTask(throwerControl);
	  startTask(controllerPolling);
	  startTask(driving);
	  while(true){
	  	delay(500);
	  }
}
